### ISSUE TITLE
Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int, float or None.

### ISSUE THREAD

**Issue by nobicycle** [c-w/gutenberg-http#6]
Thank you for your work Mr Clemens. During install I get "ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int, float or None."
$ python -V
Python 3.7.3

Best wishes

This is what I am running:

```
git clone https://github.com/c-w/gutenberg-http.git
cd gutenberg-http
docker-compose up --build web

```

After which I get this error:

> [me@tower gutenberg-http]$ docker-compose up --build web
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/requests/packages/urllib3/util/timeout.py", line 124, in _validate_timeout
>     float(value)
> TypeError: float() argument must be a string or a number, not 'Timeout'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/docker-compose", line 11, in <module>
>     load_entry_point('docker-compose==1.24.0', 'console_scripts', 'docker-compose')()
>   File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 71, in main
>     command()
>   File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 124, in perform_command
>     project = project_from_options('.', options)
>   File "/usr/lib/python3.7/site-packages/compose/cli/command.py", line 42, in project_from_options
>     compatibility=options.get('--compatibility'),
>   File "/usr/lib/python3.7/site-packages/compose/cli/command.py", line 128, in get_project
>     project_name, config_data, client, environment.get('DOCKER_DEFAULT_PLATFORM')
>   File "/usr/lib/python3.7/site-packages/compose/project.py", line 101, in from_config
>     service_networks = get_networks(service_dict, networks)
>   File "/usr/lib/python3.7/site-packages/compose/network.py", line 320, in get_networks
>     networks[network.true_name] = netdef
>   File "/usr/lib/python3.7/site-packages/compose/network.py", line 125, in true_name
>     self._set_legacy_flag()
>   File "/usr/lib/python3.7/site-packages/compose/network.py", line 146, in _set_legacy_flag
>     data = self.inspect(legacy=True)
>   File "/usr/lib/python3.7/site-packages/compose/network.py", line 106, in inspect
>     return self.client.inspect_network(self.legacy_full_name)
>   File "/usr/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
>     return f(self, resource_id, *args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/docker/api/network.py", line 211, in inspect_network
>     res = self._get(url, params=params)
>   File "/usr/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
>     return f(self, *args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 230, in _get
>     return self.get(url, **self._set_request_timeout(kwargs))
>   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/usr/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py", line 587, in urlopen
>     timeout_obj = self._get_timeout(timeout)
>   File "/usr/lib/python3.7/site-packages/requests/packages/urllib3/connectionpool.py", line 302, in _get_timeout
>     return Timeout.from_float(timeout)
>   File "/usr/lib/python3.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
>     return Timeout(read=timeout, connect=timeout)
>   File "/usr/lib/python3.7/site-packages/requests/packages/urllib3/util/timeout.py", line 94, in __init__
>     self._connect = self._validate_timeout(connect, 'connect')
>   File "/usr/lib/python3.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
>     "int, float or None." % (name, value))
> ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int, float or None.
>

**Comment by c-w** [comment]
Apologies for the late reply. I wasn't receiving notifications for this repository for a while. The build behavior you mentioned should have been fixed by f3c9881 so I'm closing this issue. Feel free to re-open if you're still experiencing problems.
